outfile:main.o add.o print.o count.o read_file.o save.o reverse.o 
	cc main.o add.o print.o count.o read_file.o save.o reverse.o -o outfile
main.o:main.c
	cc -c main.c
add.o:add.c
	cc -c add.c
print.o:print.c
	cc -c print.c
count.o:count.c
	cc -c count.c
read_file.o:read_file.c
	cc -c read_file.c
save.o:save.c
	cc -c save.c
reverse.o:reverse.c
	cc -c reverse.c

